apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: database
    tier: database
type: Opaque
stringData:
  mongo-username: admin
  mongo-password: secretpassword
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: module14
data:
  DB_HOST: database-service
  DB_PORT: "27017"
